# Generated by Django 2.2.5 on 2020-01-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('details', models.CharField(max_length=300)),
                ('birthdate', models.DateField()),
            ],
        ),
    ]
