# Generated by Django 2.2.5 on 2020-01-09 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
