# Generated by Django 2.2.5 on 2020-01-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200109_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='prouduct',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='prouduct',
            name='image',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
        migrations.AddField(
            model_name='prouduct',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prouduct',
            name='subcategory',
            field=models.CharField(default='', max_length=50),
        ),
    ]
