# Generated by Django 2.2.5 on 2020-01-20 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200109_1950'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prouduct',
            new_name='Product',
        ),
    ]
